### ISSUE TITLE
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5'

### ISSUE THREAD

**Issue by sirlattwich** [alandmoore/admbrowser#15]
![2019-11-05 15_14_21-sirlattwich@sirlattwich-ntp_~_Downloads_admbrowser](https://user-images.githubusercontent.com/26206581/68215587-cafed900-ffdf-11e9-9f9b-7227ec0127af.png)

`
[sirlattwich@sirlattwich-ntp admbrowser]$ python admbrowser.py
Traceback (most recent call last):
  File "admbrowser.py", line 1, in <module>
    from admbrowser import main
  File "/home/sirlattwich/Downloads/admbrowser/admbrowser/__init__.py", line 1, in <module>
    from .browser import *
  File "/home/sirlattwich/Downloads/admbrowser/admbrowser/browser.py", line 21, in <module>
    from PyQt5 import QtWebEngineWidgets as qtwe
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (/usr/lib/python3.7/site-packages/PyQt5/__init__.py)
`

Root cause: https://stackoverflow.com/questions/37876987/cannot-import-qtwebkitwidgets-in-pyqt5 

Solution: Add "python-pyqtwebengine" to requirements 
https://www.archlinux.org/packages/extra/x86_64/python-pyqtwebengine/

**Comment by alandmoore** [comment]
I've added the proper import to `requirements.txt`.  I'll look into the AUR packaging issue separately.
