### ISSUE TITLE
admbrowser.py needs a "crunch bang" statement

### ISSUE THREAD

**Issue by stroobandt** [alandmoore/admbrowser#21]
`admbrowser.py` needs the "crunch bang" statement `#!/usr/bin/env python` to render it executable on *nix systems as per documentation.

The documentation also needs editing as it mentions `browser.py`, whereas it should read `admbrowser.py`.

`#!/usr/bin/env python` is preferred over `#!/usr/bin/python` as this is less dogmatic about the organisation of the file system. For example, the first statement will work on BSD systems, whereas the second will not.

I have prepared two pull requests that resolve these issues:
- https://github.com/alandmoore/admbrowser/pull/18
- https://github.com/alandmoore/admbrowser/pull/19

**Comment by alandmoore** [comment]
Fixed by 5d9826d

Thanks!
