### ISSUE TITLE
Feature request: Custom window title

### ISSUE THREAD

**Issue by stroobandt** [alandmoore/admbrowser#22]
It would be nice if one could define a custom window title in the YAML file to replace the default "Browser" window title.

**Comment by stroobandt** [comment]
I programmed it myself, which was pretty easy.
If you would like to see a pull request, please, let me know here.

**Comment by alandmoore** [comment]
Please do.  make sure you add the parameter to the documentation and example configuration, please.

On November 6, 2022 8:32:51 AM CST, "Serge Y. Stroobandt" ***@***.***> wrote:
>I programmed it myself, which was pretty easy.
>If you would like to see a pull request, please, let me know here.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/alandmoore/admbrowser/issues/22#issuecomment-1304814983
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stroobandt** [comment]
Above pull request resolves this issue and adds as a bonus custom window icons.

**Comment by alandmoore** [comment]
Fixed by PR 23.  Thanks!
